name: Release / Create GitHub release
description: Creates a draft GitHub release from a release tag.
author: Steffen Diswal

inputs:
  gh-auth-token:
    description: An authentication token for the GitHub CLI with scopes for `repo` and `read:org` in order to create a release.
    required: true
  release-version:
    description: The semantic version number of the new release on the form `major.minor.patch[-prerelease][+buildinfo]` without any `v` prefix.
    required: true

runs:
  using: composite
  steps:
    - name: Validate input parameters # See https://github.com/actions/runner/issues/1070.
      run: |
        if [[ -z "$GH_AUTH_TOKEN" ]]; then
          echo "Input parameter 'gh-auth-token' must be non-empty."
          exit 2
        fi
        if [[ -z "$RELEASE_VERSION" ]]; then
          echo "Input parameter 'release-version' must be non-empty."
          exit 2
        fi
      env:
        GH_AUTH_TOKEN: ${{ inputs.gh-auth-token }}
        RELEASE_VERSION: ${{ inputs.release-version }}
      shell: bash
    - name: Create a draft release in GitHub from the corresponding Git tag
      run: |
        gh auth login --with-token <<< "$GH_AUTH_TOKEN"
        gh release create --draft --verify-tag --title "$RELEASE_VERSION" --notes "This release was created automatically by GitHub Actions." "v$RELEASE_VERSION"
      env:
        GH_AUTH_TOKEN: ${{ inputs.gh-auth-token }}
        RELEASE_VERSION: ${{ inputs.release-version }}
      shell: bash
